// SPDX-FileCopyrightText: 2024-present Deepstaging
// SPDX-License-Identifier: RPL-1.5

namespace Deepstaging.Roslyn.Tests.Emit;

public class GlobalUsingsTests
{
    private static readonly EmitOptions NoHeaders = new()
    {
        HeaderComment = "",
        LicenseHeader = null
    };

    [Test]
    public async Task Emit_single_namespace()
    {
        var result = GlobalUsings.Emit(NoHeaders, "System.Text.Json");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System.Text.Json;");
    }

    [Test]
    public async Task Emit_multiple_namespaces()
    {
        var result = GlobalUsings.Emit(NoHeaders,
            "System.Text.Json",
            "System.Collections.Generic",
            "Microsoft.Extensions.Logging");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System.Text.Json;");
        await Assert.That(valid.Code).Contains("global using System.Collections.Generic;");
        await Assert.That(valid.Code).Contains("global using Microsoft.Extensions.Logging;");
    }

    [Test]
    public async Task Emit_static_using()
    {
        var result = GlobalUsings.Emit(NoHeaders, "static System.Math");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using static System.Math;");
    }

    [Test]
    public async Task Emit_mixed_regular_and_static()
    {
        var result = GlobalUsings.Emit(NoHeaders,
            "System.Text.Json",
            "static System.Math");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System.Text.Json;");
        await Assert.That(valid.Code).Contains("global using static System.Math;");
    }

    [Test]
    public async Task Emit_from_NamespaceRef()
    {
        var result = GlobalUsings.Emit(NoHeaders,
            NamespaceRef.From("System.Text.Json"),
            NamespaceRef.From("System.Collections.Generic"));

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System.Text.Json;");
        await Assert.That(valid.Code).Contains("global using System.Collections.Generic;");
    }

    [Test]
    public async Task Emit_with_AsStatic()
    {
        var result = GlobalUsings.Emit(NoHeaders,
            NamespaceRef.From("System.Math").AsStatic());

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using static System.Math;");
    }

    [Test]
    public async Task Emit_skips_whitespace_entries()
    {
        var result = GlobalUsings.Emit(NoHeaders, "System", "  ", "System.Linq");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System;");
        await Assert.That(valid.Code).Contains("global using System.Linq;");
    }

    [Test]
    public async Task Emit_includes_header_comment()
    {
        var result = GlobalUsings.Emit("System.Text.Json");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("// <auto-generated/>");
    }

    [Test]
    public async Task Emit_includes_license_header()
    {
        var result = GlobalUsings.Emit("System.Text.Json");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("SPDX-License-Identifier");
    }

    [Test]
    public async Task Emit_default_options_uses_NamespaceRef()
    {
        var result = GlobalUsings.Emit(NamespaceRef.From("System.Text.Json"));

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("// <auto-generated/>");
        await Assert.That(valid.Code).Contains("global using System.Text.Json;");
    }

    [Test]
    public async Task Emit_returns_valid_syntax()
    {
        var result = GlobalUsings.Emit("System", "System.Linq");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Syntax.Usings).Count().IsEqualTo(2);
    }

    [Test]
    public async Task Emit_conditional_using_wraps_in_if_directive()
    {
        var result = GlobalUsings.Emit(NoHeaders, [
            "System",
            NamespaceRef.From("LanguageExt").When(Directives.Net5OrGreater)
        ]);

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System;");
        await Assert.That(valid.Code).Contains("#if NET5_0_OR_GREATER");
        await Assert.That(valid.Code).Contains("global using LanguageExt;");
        await Assert.That(valid.Code).Contains("#endif");
    }

    [Test]
    public async Task Emit_conditional_group_shares_directive_block()
    {
        var notNetStandard = Directives.NetStandard.Not();

        var result = GlobalUsings.Emit(NoHeaders, [
            "System",
            NamespaceRef.From("LanguageExt").When(notNetStandard),
            NamespaceRef.From("LanguageExt.Common").When(notNetStandard)
        ]);

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System;");
        await Assert.That(valid.Code).Contains("#if !NETSTANDARD");
        await Assert.That(valid.Code).Contains("global using LanguageExt;");
        await Assert.That(valid.Code).Contains("global using LanguageExt.Common;");
        await Assert.That(valid.Code).Contains("#endif");
    }

    [Test]
    public async Task Emit_conditional_static_using()
    {
        var result = GlobalUsings.Emit(NoHeaders, [
            NamespaceRef.From("System.Math").AsStaticWhen(Directives.Net6OrGreater)
        ]);

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("#if NET6_0_OR_GREATER");
        await Assert.That(valid.Code).Contains("global using static System.Math;");
        await Assert.That(valid.Code).Contains("#endif");
    }

    [Test]
    public async Task Emit_unconditional_entries_from_implicit_conversions()
    {
        var result = GlobalUsings.Emit(NoHeaders, [
            "System.Text.Json",
            NamespaceRef.From("System.Linq")
        ]);

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System.Text.Json;");
        await Assert.That(valid.Code).Contains("global using System.Linq;");
        await Assert.That(valid.Code).DoesNotContain("#if");
    }

    [Test]
    public async Task Emit_mixed_unconditional_and_conditional()
    {
        var result = GlobalUsings.Emit(NoHeaders, [
            "System",
            "System.Linq",
            NamespaceRef.From("LanguageExt").When(Directives.Net5OrGreater),
            NamespaceRef.From("System.Math").AsStaticWhen(Directives.Net6OrGreater)
        ]);

        await Assert.That(result.IsValid(out var valid)).IsTrue();

        // Unconditional usings come first (no directives around them)
        await Assert.That(valid.Code).Contains("global using System;");
        await Assert.That(valid.Code).Contains("global using System.Linq;");

        // Conditional usings wrapped in their respective directives
        await Assert.That(valid.Code).Contains("#if NET5_0_OR_GREATER");
        await Assert.That(valid.Code).Contains("global using LanguageExt;");
        await Assert.That(valid.Code).Contains("#if NET6_0_OR_GREATER");
        await Assert.That(valid.Code).Contains("global using static System.Math;");
    }

    [Test]
    public async Task Emit_conditional_with_default_options()
    {
        var result = GlobalUsings.Emit([
            "System",
            NamespaceRef.From("LanguageExt").When(Directives.Net5OrGreater)
        ]);

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("// <auto-generated/>");
        await Assert.That(valid.Code).Contains("#if NET5_0_OR_GREATER");
        await Assert.That(valid.Code).Contains("global using LanguageExt;");
    }
}