// SPDX-FileCopyrightText: 2024-present Deepstaging
// SPDX-License-Identifier: RPL-1.5

namespace Deepstaging.Roslyn.TypeScript.Emit;

/// <summary>
/// Options that control how TypeScript source code is emitted.
/// </summary>
public sealed class TsEmitOptions
{
    /// <summary>Gets or sets the indentation string used for each nesting level. Defaults to two spaces.</summary>
    public string Indentation { get; set; } = "  ";

    /// <summary>Gets or sets the end-of-line sequence. Defaults to <c>"\n"</c>.</summary>
    public string EndOfLine { get; set; } = "\n";

    /// <summary>Gets or sets an optional header comment emitted at the top of the file.</summary>
    public string? HeaderComment { get; set; } = "// <auto-generated/>";

    /// <summary>Gets or sets a value indicating whether to terminate statements with semicolons.</summary>
    public bool UseSemicolons { get; set; } = true;

    /// <summary>Gets or sets a value indicating whether to emit trailing commas in member lists.</summary>
    public bool UseTrailingCommas { get; set; } = true;

    /// <summary>Gets or sets a value indicating whether to use single quotes for string literals.</summary>
    public bool SingleQuotes { get; set; } = true;

    /// <summary>Gets or sets the validation level applied to emitted code. Defaults to <see cref="TsValidationLevel.None"/>.</summary>
    /// <remarks>
    /// When set to <see cref="TsValidationLevel.Syntax"/>, the emitter invokes <c>tsc --noEmit</c>
    /// to validate the generated TypeScript. Requires TypeScript to be installed (via npm or globally).
    /// Recommended for test-time validation, not source generator hot paths.
    /// </remarks>
    public TsValidationLevel ValidationLevel { get; set; } = TsValidationLevel.None;

    /// <summary>Gets or sets a value indicating whether to format the emitted code using an external formatter.</summary>
    /// <remarks>
    /// When enabled, the emitter attempts to format the code using <c>dprint</c> (preferred) or
    /// <c>prettier</c> (fallback via npx). Falls back gracefully to unformatted output if neither is available.
    /// </remarks>
    public bool FormatOutput { get; set; }

    /// <summary>Gets or sets the path to the <c>tsc</c> executable. When <c>null</c>, resolves via <c>npx</c> or PATH.</summary>
    public string? TscPath { get; set; }

    /// <summary>Gets the default emit options.</summary>
    public static TsEmitOptions Default { get; } = new();
}
