// SPDX-FileCopyrightText: 2024-present Deepstaging
// SPDX-License-Identifier: RPL-1.5

namespace Deepstaging.Roslyn.Tests.Emit;

public class GlobalUsingsTests
{
    private static readonly EmitOptions NoHeaders = new()
    {
        HeaderComment = "",
        LicenseHeader = null
    };

    [Test]
    public async Task Emit_single_namespace()
    {
        var result = GlobalUsings.Emit(NoHeaders, "System.Text.Json");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System.Text.Json;");
    }

    [Test]
    public async Task Emit_multiple_namespaces()
    {
        var result = GlobalUsings.Emit(NoHeaders,
            "System.Text.Json",
            "System.Collections.Generic",
            "Microsoft.Extensions.Logging");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System.Text.Json;");
        await Assert.That(valid.Code).Contains("global using System.Collections.Generic;");
        await Assert.That(valid.Code).Contains("global using Microsoft.Extensions.Logging;");
    }

    [Test]
    public async Task Emit_static_using()
    {
        var result = GlobalUsings.Emit(NoHeaders, "static System.Math");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using static System.Math;");
    }

    [Test]
    public async Task Emit_mixed_regular_and_static()
    {
        var result = GlobalUsings.Emit(NoHeaders,
            "System.Text.Json",
            "static System.Math");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System.Text.Json;");
        await Assert.That(valid.Code).Contains("global using static System.Math;");
    }

    [Test]
    public async Task Emit_from_NamespaceRef()
    {
        var result = GlobalUsings.Emit(NoHeaders,
            JsonRefs.Namespace,
            CollectionRefs.Namespace);

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System.Text.Json;");
        await Assert.That(valid.Code).Contains("global using System.Collections.Generic;");
    }

    [Test]
    public async Task Emit_with_AsStatic()
    {
        var result = GlobalUsings.Emit(NoHeaders,
            NamespaceRef.From("System.Math").AsStatic());

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using static System.Math;");
    }

    [Test]
    public async Task Emit_skips_whitespace_entries()
    {
        var result = GlobalUsings.Emit(NoHeaders, "System", "  ", "System.Linq");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("global using System;");
        await Assert.That(valid.Code).Contains("global using System.Linq;");
    }

    [Test]
    public async Task Emit_includes_header_comment()
    {
        var result = GlobalUsings.Emit("System.Text.Json");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("// <auto-generated/>");
    }

    [Test]
    public async Task Emit_includes_license_header()
    {
        var result = GlobalUsings.Emit("System.Text.Json");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("SPDX-License-Identifier");
    }

    [Test]
    public async Task Emit_default_options_uses_NamespaceRef()
    {
        var result = GlobalUsings.Emit(JsonRefs.Namespace);

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Code).Contains("// <auto-generated/>");
        await Assert.That(valid.Code).Contains("global using System.Text.Json;");
    }

    [Test]
    public async Task Emit_returns_valid_syntax()
    {
        var result = GlobalUsings.Emit("System", "System.Linq");

        await Assert.That(result.IsValid(out var valid)).IsTrue();
        await Assert.That(valid.Syntax.Usings).Count().IsEqualTo(2);
    }
}