// SPDX-FileCopyrightText: 2024-present Deepstaging
// SPDX-License-Identifier: RPL-1.5
using System.Diagnostics;

namespace Deepstaging.Roslyn.Testing;

/// <summary>
/// Provides extension methods for capturing and analyzing instrumentation data from effect executions during testing.
/// </summary>
/// <remarks>
/// These extensions enable test code to observe OpenTelemetry activity data generated by effects
/// that have been instrumented using the .WithInstrumentation() method. This is useful for
/// verifying that effects properly emit telemetry, track performance metrics, and record tags.
/// </remarks>
public static class EffectInstrumentationExtensions
{
    /// <param name="effect">The effect to execute. Should have .WithInstrumentation() applied to emit telemetry.</param>
    /// <typeparam name="TRuntime">The runtime environment type required by the effect.</typeparam>
    /// <typeparam name="TResult">The result type produced by the effect on success.</typeparam>
    extension<TRuntime, TResult>(Eff<TRuntime, TResult> effect)
    {
        /// <summary>
        /// Executes an effect and captures all instrumentation data emitted during its execution.
        /// </summary>
        /// <param name="runtime">The runtime environment instance to provide to the effect.</param>
        /// <param name="activitySource">The ActivitySource to monitor for capturing activity events and data.</param>
        /// <returns>
        /// A task that resolves to an <see cref="InstrumentationTestContext"/> containing the effect's result
        /// (or error), along with all captured activity data including status, tags, and duration metrics.
        /// </returns>
        /// <remarks>
        /// This method sets up an ActivityListener to capture telemetry from the specified ActivitySource,
        /// executes the effect, and returns both the execution result and all instrumentation data together.
        /// The listener is automatically disposed when the context is disposed or if an exception occurs.
        /// Both successful and failed effect executions are captured - check the context's Error property
        /// to determine if the effect failed.
        /// </remarks>
        /// <exception cref="Exception">Propagates any exceptions thrown during effect execution setup.</exception>
        public async Task<InstrumentationTestContext> CaptureInstrumentation(TRuntime runtime,
            ActivitySource activitySource)
        {
            Activity? capturedActivity = null;
            ActivityStatusCode? capturedStatus = null;
            string? capturedStatusDescription = null;
            var capturedTags = new Dictionary<string, object?>();
            long? durationMs = null;
            var wasStarted = false;

            var listener = new ActivityListener
            {
                ShouldListenTo = source => source.Name == activitySource.Name,
                Sample = (ref _) => ActivitySamplingResult.AllDataAndRecorded,
                ActivityStarted = activity =>
                {
                    capturedActivity = activity;
                    wasStarted = true;
                },
                ActivityStopped = activity =>
                {
                    capturedActivity = activity;
                    capturedStatus = activity.Status;
                    capturedStatusDescription = activity.StatusDescription;
                    
                    foreach (var tag in activity.Tags)
                    {
                        capturedTags[tag.Key] = tag.Value;
                    }

                    if (capturedTags.TryGetValue("operation.duration_ms", out var durationValue) 
                        && durationValue is long duration)
                    {
                        durationMs = duration;
                    }
                }
            };

            ActivitySource.AddActivityListener(listener);

            try
            {
                var res = await effect.RunAsync(runtime);

                var result = res.Match(
                    Succ: value => new InstrumentationTestContext(
                        capturedActivity,
                        capturedStatus,
                        capturedStatusDescription,
                        capturedTags,
                        durationMs,
                        wasStarted,
                        result: value,
                        error: null,
                        // ReSharper disable once AccessToDisposedClosure
                        listener),
                    Fail: error => new InstrumentationTestContext(
                        capturedActivity,
                        capturedStatus,
                        capturedStatusDescription,
                        capturedTags,
                        durationMs,
                        wasStarted,
                        result: null,
                        error: error,
                        // ReSharper disable once AccessToDisposedClosure
                        listener));

                return result;
            }
            catch
            {
                listener.Dispose();
                throw;
            }

        }
    }
}
