// SPDX-FileCopyrightText: 2024-present Deepstaging
// SPDX-License-Identifier: RPL-1.5

namespace Deepstaging.RoslynKit.Generators.Writers;

using Deepstaging.Roslyn.Emit;
using Projection.Models;
#if (!includeRuntime)
using Deepstaging.Roslyn.Emit.Interfaces.Observable;
#endif

/// <summary>Emit writer for AutoNotify models.</summary>
public static class AutoNotifyWriter
{
    extension(AutoNotifyModel model)
    {
        /// <summary>Builds the partial class with INotifyPropertyChanged and generated properties.</summary>
        public OptionalEmit WriteAutoNotifyClass() => TypeBuilder
#if (includeRuntime)
            .Parse($"{model.Accessibility} partial class {model.TypeName} : global::Deepstaging.RoslynKit.Runtime.ObservableObject")
#else
            .Parse($"{model.Accessibility} partial class {model.TypeName}")
#endif
            .InNamespace(model.Namespace)
            .WithXmlDoc(xml => xml
                .WithSummary($"A class generated by AutoNotifyGenerator for {model.TypeName}.")
                .WithRemarks("This class is auto-generated. Do not modify directly.")
            )
#if (!includeRuntime)
            .ImplementsINotifyPropertyChanged()
            .AddSetPropertyMethod()
#endif
            .WithEach(model.Fields, (type, field) => type
                .AddProperty(field.PropertyName, field.TypeName, p => p
                    .WithGetter(b => b.AddStatement($"return {field.FieldName}"))
                    .WithSetter(b => b.CreateSetter(field))
                    .WithXmlDoc(xml => xml
                        .WithSummary($"Gets or sets the {field.PropertyName} value.")
                        .WithRemarks($"Generated from the backing field {field.FieldName}."))))
            .Emit();
    }

    private static BodyBuilder CreateSetter(this BodyBuilder builder, AutoNotifyFieldModel field) =>
        field.AlsoNotify.Count > 0
            ? builder.AddIf($"{SetMethodName}(ref {field.FieldName}, value)", b =>
                b.WithEach(field.AlsoNotify, (body, prop) =>
                    body.AddStatement($"OnPropertyChanged(\"{prop}\")")))
            : builder.AddStatement($"{SetMethodName}(ref {field.FieldName}, value)");

#if (includeRuntime)
    private const string SetMethodName = "SetField";
#else
    private const string SetMethodName = "SetProperty";

    private static TypeBuilder AddSetPropertyMethod(this TypeBuilder builder) =>
        builder.AddMethod("SetProperty", m => m
            .AddTypeParameter("T")
            .WithReturnType("bool")
            .WithAccessibility(Accessibility.Private)
            .AddParameter("field", "T", p => p.AsRef())
            .AddParameter("value", "T")
            .AddParameter("propertyName", "string?", p => p
                .WithAttribute("global::System.Runtime.CompilerServices.CallerMemberName")
                .WithDefaultValue("null"))
            .WithBody(b => b
                .AddIf("global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(field, value)",
                    ib => ib.AddReturn("false"))
                .AddStatement("field = value")
                .AddStatement("OnPropertyChanged(propertyName)")
                .AddReturn("true")));
#endif
}