// SPDX-FileCopyrightText: 2024-present Deepstaging
// SPDX-License-Identifier: RPL-1.5

namespace Deepstaging.Roslyn.Scriban;

/// <summary>
/// Emits <c>[assembly: AssemblyMetadata]</c> attributes to advertise that a customizable
/// template is available. Uses the built-in <c>System.Reflection.AssemblyMetadataAttribute</c>
/// to avoid requiring a custom attribute type in the consumer's compilation.
/// </summary>
/// <remarks>
/// <para>Metadata keys follow a convention:</para>
/// <list type="bullet">
/// <item><c>Deepstaging.Scaffold:{templateName}</c> — value is the trigger attribute's fully qualified name</item>
/// <item><c>Deepstaging.Scaffold:{templateName}:Content</c> — value is the scaffold template content</item>
/// </list>
/// </remarks>
public static class ScaffoldEmitter
{
    /// <summary>
    /// The key prefix used for scaffold metadata attributes.
    /// </summary>
    public const string MetadataKeyPrefix = "Deepstaging.Scaffold:";

    /// <summary>
    /// The suffix appended to the template name key to store scaffold content.
    /// </summary>
    public const string ContentKeySuffix = ":Content";

    /// <summary>
    /// Emits assembly metadata attributes advertising a customizable template and its scaffold.
    /// Call this from a <see cref="SourceProductionContext"/> callback.
    /// </summary>
    /// <param name="ctx">The source production context.</param>
    /// <param name="customizable">
    /// The customizable emit from which the scaffold is computed.
    /// Must have been created via <see cref="CustomizableEmitExtensions"/>.
    /// </param>
    /// <param name="triggerAttributeFullName">
    /// The fully qualified name of the trigger attribute type
    /// (e.g., <c>"Deepstaging.Ids.StrongIdAttribute"</c>).
    /// </param>
    public static void EmitScaffold(
        SourceProductionContext ctx,
        CustomizableEmit customizable,
        string triggerAttributeFullName)
    {
        var scaffold = TemplateScaffold.Generate(customizable);
        if (scaffold is null) return;

        var escapedScaffold = scaffold.Replace("\"", "\"\"");
        var templateName = customizable.TemplateName;

        ctx.AddSource("CustomizableTemplate.g.cs",
            $$"""
              // <auto-generated/>
              [assembly: global::System.Reflection.AssemblyMetadata("{{MetadataKeyPrefix}}{{templateName}}", "{{triggerAttributeFullName}}")]
              [assembly: global::System.Reflection.AssemblyMetadata("{{MetadataKeyPrefix}}{{templateName}}{{ContentKeySuffix}}", @"{{escapedScaffold}}")]
              """);
    }
}