// SPDX-FileCopyrightText: 2024-present Deepstaging
// SPDX-License-Identifier: RPL-1.5

namespace Deepstaging.Roslyn.Scriban;

/// <summary>
/// Emits a <see cref="CustomizableTemplateAttribute"/> as generated source,
/// advertising that a customizable template is available for a given trigger attribute.
/// </summary>
public static class ScaffoldEmitter
{
    /// <summary>
    /// Emits an <c>[assembly: CustomizableTemplate(...)]</c> attribute as generated source.
    /// Call this from a <see cref="SourceProductionContext"/> callback to advertise the
    /// availability of a customizable template and its scaffold content.
    /// </summary>
    /// <param name="ctx">The source production context.</param>
    /// <param name="customizable">
    /// The customizable emit from which the scaffold is computed.
    /// Must have been created via <see cref="CustomizableEmitExtensions"/>.
    /// </param>
    /// <param name="triggerAttributeFullName">
    /// The fully qualified name of the trigger attribute type
    /// (e.g., <c>"global::Deepstaging.Ids.StrongIdAttribute"</c>).
    /// </param>
    public static void EmitScaffold(
        SourceProductionContext ctx,
        CustomizableEmit customizable,
        string triggerAttributeFullName)
    {
        var scaffold = TemplateScaffold.Generate(customizable);
        if (scaffold is null) return;

        var escapedScaffold = scaffold.Replace("\"", "\"\"");

        ctx.AddSource("CustomizableTemplate.g.cs",
            $$"""
            // <auto-generated/>
            #nullable enable
            [assembly: global::Deepstaging.Roslyn.Scriban.CustomizableTemplateAttribute(
                "{{customizable.TemplateName}}",
                typeof({{triggerAttributeFullName}}),
                Scaffold = @"{{escapedScaffold}}")]
            """);
    }
}
